# The recommended basic settings for GNN
out_dir: results
device: auto
dataset:
  format: PyG
  load_type: pointwise
  name: ml-100k
  task: link_pred
  task_type: regression
  transductive: True
  split: [0.8, 0.1, 0.1]  
  node_encoder: True
  node_encoder_name: one-hot
  edge_negative_sampling_ratio: 0.0
  encoder_dim: 64
train:
  batch_size: 4096
  eval_period: 20
  ckpt_period: 20
  ckpt_clean: False
model:
  type: mcgnn
  loss_fun: mse
  edge_decoding: dot
gnn:
  component_num: 2
  component_aggr: concat
  layers_pre_mp: 0
  layers_mp: 3
  layers_post_mp: 1
  dim_inner: 64
  layer_type: gcnconv
  stage_type: mean
  act: prelu
  dropout: 0.0
  msg: identity
  batchnorm: True 
  l2norm: True
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 200
  weight_decay: 5e-4
topk: 20
metric_best: hr_at_k
skip_existing_exp: False